name: Python Workflow 

on:
  schedule:
    - cron: '30 17 * * *'  # 11:00 PM IST (5:30 PM UTC)
    - cron: '30 0 * * *'   # 6:00 AM IST (12:30 AM UTC)
    - cron: '30 6 * * *'   # 12:00 PM IST (6:30 AM UTC)
    - cron: '10 13 * * *'  # 6:40 PM IST (1:10 PM UTC)
  push:
    branches:
      - main
 
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace '3.x' with the desired Python version

      - name: Update pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have a requirements.txt file

      - name: Run Python script
        run: |
          python .github/workflows/script.py
